#!/usr/bin/env bash

set -u

if [[ -n "$(command -v apt)" ]]; then
  sudo apt update
  xargs -a packages.txt -r -- sudo apt install -y
fi

if [[ -z "$(command -v starship)" ]]; then
  sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes
fi
