#!/bin/bash

set -u

if [[ "$(/usr/bin/uname -m)" == "arm64" ]]; then
  # On ARM macOS, this script installs to /opt/homebrew only
  HOMEBREW_PREFIX="/opt/homebrew"
else
  # On Intel macOS, this script installs to /usr/local only
  HOMEBREW_PREFIX="/usr/local"
fi

if [[ ! -x "$HOMEBREW_PREFIX/bin/brew" ]]; then
  echo "Unable to locate Homebrew, installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo
fi

if [[ -z $(command -v brew) ]]; then
  echo "Temporarily adding Homebrew bin directory to PATH"
  eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"
  echo
fi

brew bundle check || brew bundle install --no-lock
echo
