#!/usr/bin/env bash

if [[ "$(/usr/bin/uname -m)" == "arm64" ]]; then
  # On ARM macOS, this script installs to /opt/homebrew only
  HOMEBREW_PREFIX="/opt/homebrew"
else
  # On Intel macOS, this script installs to /usr/local only
  HOMEBREW_PREFIX="/usr/local"
fi

if [[ -z $(command -v brew) ]]; then
  echo "Unable to locate Homebrew, installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"
fi

if [[ -z $(command -v brew) ]]; then
  echo "ERROR: Homebrew is still not in your PATH, aborting installation."
  exit 1
fi

brew bundle check || brew bundle install --no-lock
echo

if ! grep -F -q "$HOMEBREW_PREFIX/bin" /etc/paths; then
  echo "configuring /etc/path for Homebrew"
  echo "$HOMEBREW_PREFIX/bin" | cat - /etc/paths | sudo tee /etc/paths
  echo
fi
