#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

BREW_BIN="$(brew --prefix)/bin"

if [[ ! "$(launchctl getenv PATH)" == *$BREW_BIN* ]]; then
  echo "## configuring launchctl"
  sudo launchctl config user path "$BREW_BIN:/usr/bin:/bin:/usr/sbin:/sbin"
  echo
fi

if [[ -z "${USER-}" ]]; then
  USER=$(id -un)
fi

sed -e "s|USER|$USER|g" -e "s|PWD|$PWD|g" autoupdate/Library/LaunchAgents/sample.UpdateDotfiles.plist >"autoupdate/Library/LaunchAgents/$USER.UpdateDotfiles.plist"
touch "$HOME/Library/Logs/$USER.UpdateDotfiles.log"

stow -t "$HOME" -v autoupdate

launchctl list "$USER.UpdateDotfiles" >/dev/null 2>&1 && launchctl unload -w "$HOME/Library/LaunchAgents/$USER.UpdateDotfiles.plist"
launchctl load -w "$HOME/Library/LaunchAgents/$USER.UpdateDotfiles.plist"
