{{- if not .headless }}
{{-   $fontDir := "" -}}
{{-   if eq .chezmoi.os "darwin" -}}
{{-     $fontDir = "Library/Fonts" -}}
{{-   else if eq .chezmoi.os "linux" -}}
{{-     $fontDir = ".local/share/fonts" -}}
{{-   end -}}
{{-   $fontWeights := list
        "Thin"
        "ThinItalic"
        "ExtraLight"
        "ExtraLightItalic"
        "Light"
        "LightItalic"
        "Regular"
        "Italic"
        "Medium"
        "MediumItalic"
        "SemiBold"
        "SemiBoldItalic"
        "Bold"
        "BoldItalic"
        "ExtraBold"
        "ExtraBoldItalic" -}}
{{-   range $fontWeights -}}
"{{ $fontDir }}/JetBrainsMono-{{ . }}.ttf":
  type: file
  url: "https://github.com/JetBrains/JetBrainsMono/raw/master/fonts/ttf/JetBrainsMono-{{ . }}.ttf"
  refreshPeriod: 168h
"{{ $fontDir }}/JetBrainsMonoNL-{{ . }}.ttf":
  type: file
  url: "https://github.com/JetBrains/JetBrainsMono/raw/master/fonts/ttf/JetBrainsMonoNL-{{ . }}.ttf"
  refreshPeriod: 168h
{{   end -}}
{{- end }}
