format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nodejs\
$package\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$character\
"""

[username]
format = "[$user]($style)"
style_user = "green"
style_root = "bold green"

[hostname]
format = "[@$hostname]($style)"
style = "green"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "cyan"
read_only = "!"

[git_branch]
format = "[$branch]($style) "
style = "purple"

[git_commit]
style = "bold purple"

[git_state]
style = "italic purple"

[git_status]
style = "purple"
deleted = "-"
modified = "*"

[nodejs]
format = "[$symbol($version)]($style) "
detect_files = ["package.json"]

[package]
format = "[$version]($style) "
style = "208"

[cmd_duration]
format = "[$duration]($style) "
show_notifications = true

[status]
format = "[$status]($style) "
style = "red"
disabled = false

# disable unused modules explicitly
[aws]
disabled = true

[cmake]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shell]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[vagrant]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
