---
directory: ~/Music/Library
library: ~/Music/library.db
original_date: yes
paths:
  comp: $albumartist/($year) $album%aunique{}/$track $title
  default: $albumartist/($year) $album%aunique{}/$track $title
  singleton: $albumartist/$artist - $title
plugins:
  duplicates
  embedart
  fetchart
  missing
  the
