abbr --add brewc 'brew cleanup'
abbr --add brewi 'brew install'
abbr --add brewl 'brew list'
abbr --add brews 'brew search'
abbr --add brewu 'brew update; and brew upgrade'
abbr --add brewx 'brew uninstall'
abbr --add brewU 'brew update; and brew upgrade; and brew cask upgrade; and brew cleanup'

abbr --add cask 'brew cask'
abbr --add caski 'brew cask install'
abbr --add caskl 'brew cask list'
abbr --add casks 'brew cask search'
abbr --add caskx 'brew cask uninstall'
