abbralias brewc 'brew cleanup'
abbralias brewi 'brew install'
abbralias brewl 'brew list'
abbralias brews 'brew search'
abbralias brewu 'brew update; and brew upgrade'
abbralias brewx 'brew uninstall'
abbralias brewU 'brew update; and brew upgrade; and brew cleanup'
