eval (hub alias -s fish)

# Provides abbr --add for completions, aliases for use in `eval`
abbr --add g 'git'
alias g 'git'
abbr --add ga 'git add -A'
alias ga 'git add -A'
abbr --add gam 'git amend'
alias gam 'git amend'
abbr --add gb 'git branch -vv'
alias gb 'git branch -vv'
abbr --add gba 'git branch -avv'
alias gba 'git branch -avv'
abbr --add gc 'git commit -m'
alias gbd 'git branch -d'
abbr --add gbd 'git branch -d'
alias gc 'git commit -m'
abbr --add gci 'git commit'
alias gci 'git commit'
abbr --add gco 'git checkout'
alias gco 'git checkout'
abbr --add gcob 'git checkout -b'
alias gcob 'git checkout -b'
abbr --add gd 'git diff'
alias gd 'git diff'
abbr --add gdc 'git diff --cached'
alias gdc 'git diff --cached'
abbr --add gf 'git fetch -pv'
alias gf 'git fetch -pv'
abbr --add gfa 'git fetch --all -pv'
alias gfa 'git fetch --all -pv'
abbr --add gh 'git hash'
alias gh 'git hash'
abbr --add ghc 'git hash | pbcopy'
alias ghc 'git hash | pbcopy'
abbr --add gl 'git log'
alias gl 'git log'
abbr --add glb 'git log --graph --branches'
alias glb 'git log --graph --branches'
abbr --add gp 'git push'
alias gp 'git push'
abbr --add gpf 'git push -f'
alias gpf 'git push -f'
abbr --add gpl 'git pull'
alias gpl 'git pull'
abbr --add gpu 'git push -u'
alias gpu 'git push -u'
abbr --add gr 'git remote -v'
alias gr 'git remote -v'
abbr --add gs 'git status --short'
alias gs 'git status --short'
abbr --add gsb 'git show-branch'
alias gsb 'git show-branch'
abbr --add gsh 'git show'
alias gsh 'git show'
abbr --add gst 'git status'
alias gst 'git status'
abbr --add gu 'git up'
alias gu 'git up'
