# Provides abbr for completions, aliases for use in `eval`
abbr g 'git'
alias g 'git'
abbr ga 'git add -A'
alias ga 'git add -A'
abbr gam 'git amend'
alias gam 'git amend'
abbr gb 'git branch -vv'
alias gb 'git branch -vv'
abbr gba 'git branch -avv'
alias gba 'git branch -avv'
abbr gc 'git commit -m'
alias gbd 'git branch -d'
abbr gbd 'git branch -d'
alias gc 'git commit -m'
abbr gci 'git commit'
alias gci 'git commit'
abbr gco 'git checkout'
alias gco 'git checkout'
abbr gcob 'git checkout -b'
alias gcob 'git checkout -b'
abbr gd 'git diff'
alias gd 'git diff'
abbr gdc 'git diff --cached'
alias gdc 'git diff --cached'
abbr gf 'git fetch -pv'
alias gf 'git fetch -pv'
abbr gfa 'git fetch --all -pv'
alias gfa 'git fetch --all -pv'
abbr gh 'git hash'
alias gh 'git hash'
abbr ghc 'git hash | pbcopy'
alias ghc 'git hash | pbcopy'
abbr gl 'git log'
alias gl 'git log'
abbr glb 'git log --graph --branches'
alias glb 'git log --graph --branches'
abbr gp 'git push'
alias gp 'git push'
abbr gpf 'git push -f'
alias gpf 'git push -f'
abbr gpl 'git pull'
alias gpl 'git pull'
abbr gpu 'git push -u'
alias gpu 'git push -u'
abbr gr 'git remote -v'
alias gr 'git remote -v'
abbr gs 'git status --short'
alias gs 'git status --short'
abbr gsb 'git show-branch'
alias gsb 'git show-branch'
abbr gsh 'git show'
alias gsh 'git show'
abbr gst 'git status'
alias gst 'git status'
abbr gu 'git up'
alias gu 'git up'
