eval (hub alias -s fish)

# Provides abbralias for completions, aliases for use in `eval`
abbralias g 'git'
abbralias ga 'git add -A'
abbralias gam 'git amend'
abbralias gb 'git branch -vv'
abbralias gba 'git branch -avv'
abbralias gc 'git commit -m'
abbralias gbd 'git branch -d'
abbralias gci 'git commit'
abbralias gco 'git checkout'
abbralias gcob 'git checkout -b'
abbralias gd 'git diff'
abbralias gdc 'git diff --cached'
abbralias gf 'git fetch -pv'
abbralias gfa 'git fetch --all -pv'
abbralias gh 'git hash'
abbralias ghc 'git hash | pbcopy'
abbralias gl 'git log'
abbralias glb 'git log --graph --branches'
abbralias gp 'git push'
abbralias gpf 'git push -f'
abbralias gpl 'git pull'
abbralias gpu 'git push -u'
abbralias gr 'git remote -v'
abbralias gs 'git status --short'
abbralias gsb 'git show-branch'
abbralias gsh 'git show'
abbralias gst 'git status'
abbralias gsy 'git fetch --all -pv; and git sync'
abbralias gu 'git up'
