# Provides abbralias for completions, aliases for use in `eval`
abbralias g git
abbralias ga "git add -A"
abbralias gam "git amend"
abbralias gb "git branch -vv"
abbralias gba "git branch -avv"
abbralias gbd "git branch -d"
abbralias gbD "git branch -D"
abbralias gbr "gh browse"
abbralias gc "git commit -m"
abbralias gci "git commit"
abbralias gco "git checkout"
abbralias gcob "git checkout -b"
abbralias gcp "git cherry-pick"
abbralias gd "git diff"
abbralias gdc "git diff --cached"
abbralias gf "git fetch"
abbralias gfa "git fetch --all -Pp"
abbralias gfv "git fetch -v"
abbralias gha "git hash"
abbralias ghac "git hash | pbcopy"
abbralias gl "git log"
abbralias glb "git log --graph --branches"
abbralias gp "git push"
abbralias gpf "git push -f"
abbralias gpl "git pull"
abbralias gpu "git push -u"
abbralias gr "git remote -v"
abbralias grb "git rebase"
abbralias grbc "git rebase --continue"
abbralias gs "git status -s"
abbralias gsb "git show-branch"
abbralias gsh "git show"
abbralias gst "git status"
abbralias gsy "gh repo sync"
abbralias gu "git up"
abbralias guc "git uncommit"
