# Usage: `brew bundle`
tap "homebrew/bundle"
tap "homebrew/command-not-found"
tap "homebrew/versions"

# Install GNU core utilities
# see zshrc GNU-utils
brew "coreutils"
brew "binutils"
brew "findutils"
brew "moreutils"
brew "gawk"
brew "gnu-sed"
brew "gnu-tar"

# Install other useful binaries
brew "bash"
brew "diff-so-fancy"
brew "direnv"
brew "fasd"
brew "flow"
brew "git-lfs"
brew "git"
brew "heroku-toolbelt"
brew "hr"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "lastpass-cli", args: ["with-pinentry"]
brew "lesspipe", args: ["with-syntax-highlighting"]
brew "mas"
brew "node-build"
brew "node"
brew "nodenv"
brew "openssl"
brew "p7zip"
brew "python"
brew "rbenv"
brew "readline"
brew "redis"
brew "rename"
brew "ruby-build"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "thefuck"
brew "tree"
brew "wget", args: ["enable-iri"]
brew "wifi-password"
brew "zsh"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"

# Install Applications
cask "aerial"
cask "alfred"
cask "appcleaner"
cask "atom"
cask "bartender"
cask "beardedspice"
cask "cheatsheet"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-drive"
cask "google-hangouts"
cask "iterm2"
cask "kap"
cask "karabiner-elements"
cask "keyboard-cleaner"
cask "postico"
cask "resilio-sync"
cask "scroll-reverser"
cask "spectacle"
cask "transmission"
cask "transmit"
cask "ubersicht"
cask "unity-web-player"
cask "virtualbox"
cask "vlc"
cask "whatsapp"
cask "xld"
cask "xquartz"

# Install Mac App Store Applications
# mas "Caffeine", id: 411246225
mas "Growl", id: 467939042
mas "Keynote", id: 409183694
mas "Monit", id: 1014850245
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
