"$schema" = "https://starship.rs/config-schema.json"

format = """
($username$hostname )\
$directory\
($git_branch$git_commit )\
$git_state\
$git_status\
$c\
$nodejs\
$python\
$ruby\
$rust\
$package\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$character\
"""

command_timeout = 1000

[username]
disabled = false
format = "[$user]($style)"
style_root = "bold green"
style_user = "green"

[hostname]
disabled = false
format = "[@$hostname]($style)"
style = "dimmed green"

[directory]
disabled = false
style = "cyan"
read_only = "!"
read_only_style = "italic red"
repo_root_style = "bold cyan"
truncation_length = 5

[git_branch]
disabled = false
format = "[$branch(:$remote_branch)]($style)"
style = "purple"

[git_commit]
disabled = false
format = "[#$hash(@$tag)]($style)"
style = "dimmed purple"
tag_disabled = false
tag_symbol = ""

[git_state]
disabled = false
style = "italic purple"

[git_status]
disabled = false
style = "purple"
deleted = "-"
modified = "*"

[c]
disabled = false
detect_files = ["binding.gyp"]
format = "[$name:$version ]($style)"
style = "51"

[nodejs]
disabled = false
format = "[node:$version ]($style)"
style = "green"
not_capable_style = "dimmed green"

[python]
disabled = true # temporarily disable
format = "[py:$pyenv_prefix($version )(\\($virtualenv\\) )]($style)"
style = "yellow"
pyenv_version_name = true

[ruby]
disabled = true # temporarily disable
format = "[ruby:$version ]$(style)"
style = "red"

[rust]
disabled = false
format = "[rs:$version ]($style)"
style = "red"

[package]
disabled = false
format = "[pkg:$version ]($style)"
style = "208"

[cmd_duration]
disabled = false
format = "[$duration]($style) "
show_notifications = false

[battery]
disabled = false
format = "[$percentage]($style) "

[status]
disabled = false
format = "[$status]($style) "
style = "red"
pipestatus = true
pipestatus_separator = ""
pipestatus_format = "[$pipestatus]($style)"

[character]
disabled = false
format = "$symbol "
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
vimcmd_replace_symbol = "[❮](purple)"
vimcmd_replace_one_symbol = "[❮](purple)"
vimcmd_visual_symbol = "[❮](yellow)"
